### ISSUE TITLE
/r/EvelynnMains 30x30px flairs

### ISSUE THREAD

**Issue by MingweiSamuel** [ChampionMains/dynamicflairs#2]
Need 30x30 px skins and ability icons, and old skins and icons if possible.

**Comment by AlexPJiang** [comment]
@ChampionMains/cream-squad-69

**Comment by MingweiSamuel** [comment]
df2f1fb3e3336142db2dc4b1116e24eac66c5bc9 images cropped

**Comment by MingweiSamuel** [comment]
676af83fab72be2005aaf4e72f9d294df31e6e32 css/page added
